### ISSUE TITLE
Problem in executing using GUIX studio 6.1.0.0 in windows OS

### ISSUE THREAD

**Issue by armembedded** [azure-rtos/guix#12]
I installed GUIX studio 6.1.0.0 in the windows operating system but the program does not start and display an error. 

how to resolve these issues?

error message title: 
The procedure entry point UiaDisconnectProvider could not be located in the dynamic link library UIAutomationCore.DLL

**Comment by jdeere5220** [comment]
Can you provide your complete Windows version information please? Thank you!

**Comment by jdeere5220** [comment]
I believe this error is caused by running an old version of Windows. You need to run minimum Windows 8, and starting next year Windows 10.

**Comment by armembedded** [comment]
> Can you provide your complete Windows version information please? Thank you!

Windows 7 ultimate

**Comment by jdeere5220** [comment]
Yes, you will need to update to Windows 10 to run GUIX Studio and TraceX applications.

**Comment by yuxin-azrtos** [comment]
Looks like this issue is resolved.  Close it.  Feel free to reopen it if you have additional comments or feedback. Thanks!
