### ISSUE TITLE
circular_gauge  Control error

### ISSUE THREAD

**Issue by geek-slt** [azure-rtos/guix#13]
GUIX version: 6.1.0
Windows： windows10 x64
question：
I used GUIX Studio to create a display page with progress bar, buttons and other controls. These controls can be controlled normally, but when I use the circle_gauge control, there is a problem. I change the angle of the needle every once in a while, and then read Angle, the angle value will change, but no needle is displayed on the screen. The needle will disappear as long as the function gx_circular_gauge_angle_set() is called. Why is this?

**Comment by jdeere5220** [comment]
This can be caused by using a compressed pixelmap for the needle image. The gauge performs runtime pixelmap rotation to rotate the gauge needle, and runtime rotation can only be done on uncompressed image. Right click on the image in GUIX Studio, Edit Settings, and make sure the "compress" option is turned off.

If that isn't the problem please get back to me and if possible attach your project.

**Comment by geek-slt** [comment]
It seems that the needle can be displayed normally, but there are some residual images. I will continue to check. I am very interested in ThreadX and GUIX. Can I continue to ask you if I encounter problems later




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azure-rtos/guix"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 晚上10:52
收件人:&nbsp;"azure-rtos/guix"<guix@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [azure-rtos/guix] circular_gauge  Control error (#13)





 
This can be caused by using a compressed pixelmap for the needle image. The gauge performs runtime pixelmap rotation to rotate the gauge needle, and runtime rotation can only be done on uncompressed image. Right click on the image in GUIX Studio, Edit Settings, and make sure the "compress" option is turned off.
 
If that isn't the problem please get back to me and if possible attach your project.

**Comment by jdeere5220** [comment]
Yes, of course, we are here to help. Send me your project and your images if you aren't able to resolve the problem so that I can dig into it. Another option is to compare your usage with our samples that use the circular gauge control.

**Comment by yuxin-azrtos** [comment]
@geek-slt are you able to share your project with @jdeere5220?  Looking forward to your feedback.

**Comment by geek-slt** [comment]
Ok&nbsp;
Thank you very much, I will do as you say




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azure-rtos/guix"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 上午6:26
收件人:&nbsp;"azure-rtos/guix"<guix@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [azure-rtos/guix] circular_gauge  Control error (#13)





 
@geek-slt are you able to share your project with @jdeere5220?  Looking forward to your feedback.

**Comment by jdeere5220** [comment]
No additional feedback, I will assume the suggestion fixed the issue reported.
