### ISSUE TITLE
2bpp font support

### ISSUE THREAD

**Issue by WeizhongFan** [azure-rtos/guix#15]
For device that has very limited storage, even 4bpp font may result in a large resource bin file. Is it possible to add 2bpp font support in guix source and studio?

**Comment by jdeere5220** [comment]
It's a reasonable request. I have added this request to our feature backlog, but I can't give you an estimate as to when we would be able to get to this. Can you tell me a little more about your project, your target hardware, and what color depth you are using?

**Comment by yuxin-azrtos** [comment]
This issue is now tracked internally. Close it.
