### ISSUE TITLE
Circular gauge doesn't display correctly

### ISSUE THREAD

**Issue by Merc359** [azure-rtos/guix#19]
Hi, 
I'm currently working on an interface that already has many windows (more than 30).
As soon as I add a cicular gauge widget (size 100px by 100 px) and change window and go back it colapse to a tiny little 2px by 2px.
Even though the data displays 100px by 100 px. This is purely through the use of the guix interface.

Thank you.
![guix_bug_blur](https://user-images.githubusercontent.com/83370744/116461675-8bacf380-a836-11eb-8f0b-b93115abf0bd.PNG)

**Comment by jdeere5220** [comment]
Hmmm that's interesting. I did a quick test to try and duplicate the issue, but so far it works fine. When I switch between window and window_1, nothing strange happens. I also tried this with samples/guix_widget_types.gxp, which includes a circular gauge window, and that also seems to come back fine. I can't see all of your gauge properties in your screen shot, can you compare your gauge to the gauge(s) in the guix_widget_types.gxp sample and detect what might be different? I will keep poking around but we need to reproduce what you are seeing. Thanks!

![image](https://user-images.githubusercontent.com/65032143/116466426-75a23180-a83c-11eb-82e7-8ba565407191.png)

**Comment by jdeere5220** [comment]
@Merc359 tag you to be sure you see reply above.

**Comment by Merc359** [comment]
Hi,

Here is the problem in video.
Thanks


https://user-images.githubusercontent.com/83370744/116564187-be0c2e80-a8d2-11eb-8292-ac42e9bcaac9.mp4

**Comment by jdeere5220** [comment]
@Merc359  I was able to reproduce the problem. We will fix it asap and push a new Studio release. For a work-around, I believe if you assign a background image to the gauge this will not happen. The issue is caused by the circular gauge attempting to auto-resize to fit the gauge background image. If there is no background image the gauge becomes very small.

**Comment by Merc359** [comment]
That is good news. I will assign a background like you've suggested until the fix is released.
Thank you for the quick response and have a good day.
