### ISSUE TITLE
Crash while generating 

### ISSUE THREAD

**Issue by Merc359** [azure-rtos/guix#22]
Hi,
I'm getting a Guix Software crash when I try to generate ressources. 
Is there a log file somewhere I can send you and where is it located?

Thank you.

**Comment by jdeere5220** [comment]
@Merc359 I'm probably going to need your project so that I can duplicate the issue. Can you zip everything up for me? We would never disclose your project outside our immediate need to replicate the issue.

**Comment by Merc359** [comment]
Hi Jdeere,
I could send you our code via wetransfer or another way. Can you give me your email address so I can proceed?
Thank you

**Comment by jdeere5220** [comment]
Hello @Merc359 , please use ken.maxwell@microsoft.com  Thanks!

**Comment by jdeere5220** [comment]
Fixed in GUIX Studio update 6.1.8.0
