### ISSUE TITLE
Can't add pixelmap horizontal bar in string scroll wheel

### ISSUE THREAD

**Issue by Merc359** [azure-rtos/guix#25]
Hi,

I'm trying to add a horizontal bar between every strings in my scroll wheel, 
but it only displays one of them.  

Thanks

**Comment by jdeere5220** [comment]
I think you will need to use a generic scroll wheel, using gx_generic_scroll_wheel_create(). A string scroll wheel only accepts strings for each row. You will probably need to create a widget that is a window containing a string and a horizontal scroll, and populate the scroll wheel with instances of this combination widget. Hope this makes sense, let me know if you need more input.
