### ISSUE TITLE
Off by one bug in win32 display driver

### ISSUE THREAD

**Issue by Fiebbo** [azure-rtos/guix#26]
The win32 simulation draws a single pixel white line on the right and bottom of the window. To fix, append a `-1` to the following lines.

https://github.com/azure-rtos/guix/blob/890c37ab95df9a87f169ab157cf1ce5e40d4e68b/ports/win32/src/gx_win32_display_driver.c#L1202-L1203

**Comment by jdeere5220** [comment]
Fixed for 6.1.9.0 release.
