### ISSUE TITLE
Macros incorrectly terminated with a semicolon

### ISSUE THREAD

**Issue by brhans-acuity** [azure-rtos/guix#28]
I've noticed 2 macros in gx_api.h are incorrectly terminated with a semicolon:
 - gx_single_line_text_input_buffer_clear on line 4778
 - gx_single_line_text_input_buffer_get on line 4779

I haven't spotted any others, but I haven't done an exhaustive search.

**Comment by jdeere5220** [comment]
Thanks for the feedback, and thanks for spotting this. It's been fixed, and the fix will be in the next scheduled update release.

**Comment by jdeere5220** [comment]
Fixed for next release.
