### ISSUE TITLE
The circle of the needle of circular gauge is not fixed when needle rotates

### ISSUE THREAD

**Issue by WeizhongFan** [azure-rtos/guix#29]
It can be reproduced by the official example demo_guix_widget_types.

When we change the gauge value, the needle rotates. But we can see that the circle of needle shifts a bit both vertically and horizontally along with the angle change.

![needle](https://user-images.githubusercontent.com/77432269/143207039-ec3a756a-463a-43bd-ab34-43235e6ae066.jpg)

**Comment by ting-ms** [comment]
Please make sure the property "Needle Xcor" and "Needle Ycor" are set properly.
<img width="264" alt="circular_gauge_properties" src="https://user-images.githubusercontent.com/65648712/143209645-cc5d8ade-a636-4ab2-8c6c-88db17700008.png">

"Needle Xcor" is the distance from the left of the needle image to the center of rotation of the gauge needle.
"Needle Ycor" is the distance from the top of the needle image to the center of rotation of the gauge needle.
Please reference the documentation about GX_CIRCULAR_GAUGE_INFO.
[![image](https://user-images.githubusercontent.com/65648712/143210281-cb740336-e7be-4f7b-9d1a-e3c46d9194b1.png)
](https://docs.microsoft.com/en-us/azure/rtos/guix/appendix-i#gx_circular_gauge_info)

**Comment by WeizhongFan** [comment]
Hi, Ting

Thanks for the quick reply.

I set exactly same params as you, but the shift can still be seen. It's very little shift, looks like just 1 pixel. But we're making a smart watch, and we use it for a second needle of a watch face. The second needle keeps rotating, so the shifts is observable by users.
![Uploading f105bc374d57bd1e736168ad2d80255.jpg…]()
![4b8ba24bb18c3fef30df43240edfbd5](https://user-images.githubusercontent.com/77432269/143220609-c3dbc182-dab6-4410-bc10-27995e5f66c8.jpg)

**Comment by WeizhongFan** [comment]
Upload again.

![f105bc374d57bd1e736168ad2d80255](https://user-images.githubusercontent.com/77432269/143220911-209d00a2-8755-4969-a0d2-b8663d350654.jpg)

**Comment by ting-ms** [comment]
GUIX supports integer numbers only for the Needle Xcor and Ycor. The specified Xcor and Ycor are not exactly the center of the circle(half pixel error). That may cause drifting when rotating. My recommendation is to change the needle image so that the actual coordinates of the circle center are integer numbers.

**Comment by jdeere5220** [comment]
Hello @WeizhongFan,

Can you make the change suggested and does this fix the issue? I need to know if we can close the issue or if we need to add a task to our backlog to investigate sub-pixel coordinates.
