### ISSUE TITLE
Threads with priority lower (higher value) than win32_driver_thread don't get scheduled

### ISSUE THREAD

**Issue by Fiebbo** [azure-rtos/guix#33]
Obviously this is only an issue on the win32 build, I'm not sure why it happens but a quick fix is to set the priority of the driver thread to `TX_MAX_PRIORITIES - 1`. Will this have any unwanted side effects?
https://github.com/azure-rtos/guix/blob/890c37ab95df9a87f169ab157cf1ce5e40d4e68b/ports/win32/inc/gx_port.h#L92-L96

**Comment by ting-ms** [comment]
Hi Fiebbo, this is an issue in Win32 driver, we'll fix it in the future. For now, you can set a lower priority to win32_driver_thread so that your threads can get scheduled.
