### ISSUE TITLE
bug about  guix\samples\demo_guix_car_infotainment\volume_screen_base.c

### ISSUE THREAD

**Issue by wlyly1** [azure-rtos/guix#37]
UINT volume_progress_bar_event_process(GX_PROGRESS_BAR *bar, GX_EVENT* event_ptr)
{
 ............
//  this should be fixed like this:
    VOLUME_SCREEN_BASE_CONTROL_BLOCK *base = (VOLUME_SCREEN_BASE_CONTROL_BLOCK *)bar->gx_widget_parent->gx_widget_parent->gx_widget_parent;

**Comment by ting-ms** [comment]
Thank you for the advice! We will fix this in the next release.
