### ISSUE TITLE
Does GUIX support software layer？

### ISSUE THREAD

**Issue by BeeeeeeLazy** [azure-rtos/guix#41]

**Comment by jdeere5220** [comment]
Yes, at many levels. You can create multiple drawing canvas, and they will be blended together in a composite canvas. You need to create the composite canvas sometime during startup, using the GX_CANVAS_COMPOSITE canvas style. You can also bind canvases to hardware graphics layers (if supported in hardware) using gx_canvas_hardware_layer_bind(). On a more basic level GUIX keeps track of z-order for widgets added to the root window. I'm not entirely sure what you are asking so I wanted to add that as well.
