### ISSUE TITLE
为什么会进Hardfalut 

### ISSUE THREAD

**Issue by LiuChenghu** [azure-rtos/guix#44]
![54d87a86fa15889ad06fe53c267153c](https://user-images.githubusercontent.com/30891935/184063599-32f5bc91-efb0-4814-a8cd-4872fdf49d39.jpg)
在如图所示的地方进Hardfalut,这什么原因导致的呢。

**Comment by jdeere5220** [comment]
I'm going to need quite a bit more information here. Can you tell me what the application is doing that leads to this? Has the child widget somehow been attached to multiple parents?

**Comment by LiuChenghu** [comment]
使用的是ThreadX + GuiX，做的是一个小弹窗，弹出一个小的界面，这个现象不是每次都会出现进入Hardfault,而是偶尔出现一次。
![image](https://user-images.githubusercontent.com/30891935/184177888-33f44ba0-cfb2-4027-a32e-a8d702eef62f.png)从图中进入，小弹窗，下面是这个图片是弹窗的实现
![image](https://user-images.githubusercontent.com/30891935/184178632-ab7c756a-7f9f-4907-b139-8e135c09ba74.png)
显示的静态内容如下
![image](https://user-images.githubusercontent.com/30891935/184178714-5242fc71-c441-4f37-a25e-5a55ddd2404f.png)

**Comment by jdeere5220** [comment]
I don't like that last line:

**g_pPopPartTimeScreen->gx_widget_parent = parent;**

You shouldn't directly assign the gx_widget_parent member. There could be another parent that already has g_pPopPartTimeScreen as a child, which would lead to the issue you originally reported. You should use an API, such as 

gx_widget_attach(parent, g_pPopPartTimeScreen); 

instead. That will automatically detach the g_pPopPartTimeScreen if it was previously attached somewhere else. Let me know if this fixes the problem.
