### ISSUE TITLE
GUIX Studio Rotation setting does not take effect

### ISSUE THREAD

**Issue by SheryWang** [azure-rtos/guix#47]
GUIX Studio Rotation setting does not take effect，CW/CCW generating data makes no difference...
How do I use GUIX Studio to change my screen from horizontal to vertical

**Comment by jdeere5220** [comment]
Hello @SheryWang,

Can you tell me a little bit more about your environment? What color depth are you using, and what is your hardware target?

The screen rotation settings are intended to be used when your display is not mounted on your device in native orientation. In that case GUIX Studio generates resource data such that rendering is still optimal without requiring any special acrobatics on the target side. You do of course need to use a GUIX display driver intended for rotation.

If you want to change from horizontal to vertical at runtime, that's a different question. Again please provide me more details and I will try to help you.

Best Regards
