### ISSUE TITLE
Incorrect PNG function being called when 2d engine is disabled

### ISSUE THREAD

**Issue by int-bio** [azure-rtos/guix#60]
**Describe the bug**
When disabling the 2d engine and setting PNG to software, GUIX Studio will still call out the 2D engine function.

Please also mention any information which could help others to understand
the problem you're facing:
- Building for cortex_m4
- Azure tx_api 6.1.10

What toolchain and environment?
- Azure RTOS GUIX Studio 6.2.1.0
- e2 Studios 2022-04 (22.4.0)
- Renesas SSP 2.3.0

What have you tried to diagnose or workaround this issue?
- Nothing comes to mind other then overriding the output before I compile.

**To Reproduce**
1. Open GUIX Studio and goto Advanced Settings
2. Deselect 2D Engine
3. Set JPEG to None
4. Set PNG to Software Decoder
5. Save and rebuild all output files

**Expected behavior**
The following code is from gui_specifications:

```
#if defined(GX_TARGET_WIN32) || defined(GX_TARGET_LINUX)

UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    win32_graphics_driver_setup_565rgb(display);
    return GX_SUCCESS;
}
#else
UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    _gx_display_driver_565rgb_setup(display, GX_NULL, _gx_synergy_buffer_toggle);
    display->gx_display_handle =    0;
    display -> gx_display_driver_png_draw   = _gx_dave2d_png_draw;
    return GX_SUCCESS;
}
#endif
```

Expected the function to be:
display -> gx_display_driver_png_draw   = _gx_display_driver_565rgb_png_draw;

**Impact**
Unable to link without errors.

**Logs and console output**
../src/gui/gui_specifications.c:18664: undefined reference to `_gx_dave2d_png_draw'

**Comment by int-bio** [comment]
![setup](https://user-images.githubusercontent.com/108280402/226354125-3d8dc1ac-bd55-4dbd-900d-e85afbfd9369.png)

**Comment by ting-ms** [comment]
GX_SOFTWARE_DECODER_SUPPORT should be defined to enable PNG decoding, would you please check if you have this configuration defined?

**Comment by ting-ms** [comment]
GUIX Studio version 6.2.1.3 has been released to Microsoft Store, and it includes the fix.
