### ISSUE TITLE
Bad LowerCase/UpperCase file loading in recent file window

### ISSUE THREAD

**Issue by xNiux** [azure-rtos/guix#61]
**Describe the bug**
When you loading a project with Recent Project window or menu, the project file is loading in lowercase instead of real case name.
When you generate files, the project name is used with the loaded case name instead real case name

Please also mention any information which could help others to understand
the problem you're facing:
- GuiX Studio version : 6.2.1.2
- Environment : Windows 10

**To Reproduce**
1. Create a project with different lower/upper case like "GuixProject.gxp"
2. Open It  with a double click on the file in file explorer : File is correctly loaded (GuixProject.gxp)
3. Generate files : All reference of project name are "GuixProject_****"
4. Close Guix Studio
5. Open Guix Studio, the Recent Projects window will list all project .... In lower case !
6. Open with Recent Projects Window your "GuiProject.gxp" : File is lowercase loaded (guixproject.gxp)
7. Generate files : All reference of project name are "guixproject_****"

**Impact**
Compilation with error because of bad variable/constant name (C is case sensitive)

![recentWindow](https://github.com/azure-rtos/guix/assets/25155398/99a16c75-218f-4e16-b646-836697ac05da)
![CompareSpecificationC1](https://github.com/azure-rtos/guix/assets/25155398/db4d90b5-f26e-46c5-8158-ba0324a2c3e8)
![CompareSpecificationC2](https://github.com/azure-rtos/guix/assets/25155398/a253f432-e89b-40fd-963a-ead8e1adb78b)
![DoubleclickOpen](https://github.com/azure-rtos/guix/assets/25155398/47ecf6ac-61ad-4e2f-890c-99e3068d7be2)
![DoubleclickOpen2](https://github.com/azure-rtos/guix/assets/25155398/67ec0310-769c-4d0d-ad9d-8fa3413c182c)
![recentOpen](https://github.com/azure-rtos/guix/assets/25155398/5b06ff5f-8f20-4348-acab-5f36ef0d8992)

**Comment by ting-ms** [comment]
Hi xNiux, I'm able to reproduce the issue, and we'll fix it.

**Comment by ting-ms** [comment]
Hi xNiux, we have fixed the issue, and will be included in the next release.

**Comment by zhutnana** [comment]
GUIX Studio version 6.2.1.3 has been released on the Microsoft Store, and it includes the fix.

**Comment by ting-ms** [comment]
GUIX Studio version 6.2.1.3 has been released to Microsoft Store, and it includes the fix.
