### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by mg-dg** [azure-rtos/guix#63]
**Describe the bug**
The documentation is very poor for GUIX, for example, a typo with **gx_progress_bar_pielmap_set**   clearly this should be gx_progress_bar_pi**x**elmap_set

Generally, there also other holes in the documentation.

**Comment by ting-ms** [comment]
Thanks for your feedback! We'll improve it.

**Comment by mg-dg** [comment]
Another one here:

https://learn.microsoft.com/en-us/azure/rtos/guix/chapter-4

**GX_BRSUH** my_brush;
GX_FONT *font;
GX_COLOR fill_color;
GX_COLOR line_color;

**Comment by ting-ms** [comment]
Thanks for your feedback! We will improve the documentation.

**Comment by ting-ms** [comment]
GUIX online documentation has been updated with the above typo fixes.
