### ISSUE TITLE
4bit per pixel png image support

### ISSUE THREAD

**Issue by flyflyfly001** [azure-rtos/guix#64]
I'm using a 4bpp frame buffer.  Is png decode and draw function support it ?

**Comment by ting-ms** [comment]
You can decode a PNG to GUIX support pixelmap format first, then draw the decoded map with gx_canvas_pixelmap_draw API.
Here's a sample code snippet demonstrating how to decode a PNG image into a 4bpp pixelmap format:
```c
GX_PIXELMAP *pixelmap;
GX_PIXELMAP decoded_map;
GX_IMAGE_READER image_reader;

gx_image_reader_create(&image_reader,  pixelmap->gx_pixelmap_data, pixelmap->gx_pixelmap_data_size, GX_COLOR_FORMAT_4BIT_GRAY, 0);

status = gx_image_reader_start(&image_reader, &decoded_map); 
```

**Comment by ting-ms** [comment]
Closing the issue.
