### ISSUE TITLE
GUIX Studio font heights above 240 pixels are not possible

### ISSUE THREAD

**Issue by IvanThor** [azure-rtos/guix#67]
Setting the font heights in GUIX studio to more than 240 pixels, e.g. 255 pixels, results in faulty behaviour. The font view doesn't show the font anymore. Moreover the font isn't shown when used in a prompt widget.
If the generated project is used with the actual hardware, the faulty behaviour stays. The font is not shown.

GUIX Studio 6.3.0.0

1. Create a new GUIX studio project
2. Add a custom font to the project and set font heigth to 255 pixels.

**Comment by ting-ms** [comment]
@IvanThor GUIX keeps track of a metric within the GX_FONT structure called gx_font_line_height. This metric represents the sum of the maximum ascent and the maximum descent of the font glyphs. It's possible that the line height can exceed the font height, as explained in more detail at https://learn.microsoft.com/en-us/azure/rtos/guix/guix-studio-4#font-resources.  In your case, when the font height is set to a value greater than 240, the resulting line height may surpass the 255 limit of the line height. We'll add a note about this in the future.

**Comment by IvanThor** [comment]
@ting-ms Disabling ASCII as character range and just include character set defined by String Table fixed the issue indeed.

![grafik](https://github.com/azure-rtos/guix/assets/42200354/a9dce455-899a-44d8-a49a-fc165666fab1)

Thank you very much
