### ISSUE TITLE
keys operation support

### ISSUE THREAD

**Issue by zjm1060** [azure-rtos/guix#7]
I am evaluating the use of GUIX as a user interface in a new project，Our device does not have a touch screen, only a cross button and a few function buttons，Can GUIX support key-based operations, such as switching of widgets focus, input methods, etc.

**Comment by goldscott** [comment]
Hi @zjm1060 - GUIX can support any input method you choose (touchscreen, keyboard, mouse, buttons, etc). GUIX is event-based - so you can send it key-down (button-down) and key-up (button-up) events and it will act on them.
